---
title: "Nos Analizamos"
author: "Yu Jing Zhou"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
# 1. Elegir plantilla
# 2. Cargar librerías (pracma, p_load)
# 3. Borrar todas las variables rm(list=ls())
# 4. Cargar los datos
#   - Averiguar codificación si los datos son de tipo texto
#   - ReadLines(NOT TABULAR; - LECT. TABULAR(readr)
# 5. Ver estructura e identificar tipo de variables

# Si tiene un 50% de datos faltantes, lo sensato sería quitarlo
```

Carga de las librerías

```{r}
# Carga de las librerías

if (!require(pacman)) install.packages("pacman")

pacman::p_load(
  readr,
  tidyverse,
  dplyr,
  knitr,
  GGally
)
```



Importación de los datos

```{r}
datos <- read_tsv("data/NosAutoanalizamos2022.tsv", skip = 25) %>%
  filter(!is.na(Id)) %>% select(-1) 

datos <- datos %>%
  mutate(Wr.Hnd = as.numeric(str_replace(Wr.Hnd, ",", "."))) %>%
  filter(Id != "martsobm") %>%
  mutate(across(c(ALG, ANM, FP, DCS, MD),
      ~ .x %>% 
        str_replace(",", ".") %>%    
        str_replace("^NC$", "3") %>% 
        as.numeric()))


notas_limpias <- datos %>% 
  select(ALG, ANM, FP, DCS, MD)

save(notas_limpias, file = "data/Notas.Rdata")
```

Estadísticos

```{r}
tabla_est <- datos %>%
  select(ALG, ANM, FP, DCS, MD) %>%
  pivot_longer(
    cols = everything(),
    names_to = "Asignatura",
    values_to = "Nota") %>%
  group_by(Asignatura) %>%
  summarise(
    val_min = round(min(Nota, na.rm = TRUE), 2),
    percentil_25 = round(quantile(Nota, 0.25, na.rm = TRUE), 2),
    mediana = round(median(Nota, na.rm = TRUE), 2),
    media = round(mean(Nota, na.rm = TRUE), 2),
    desv_tip = round(sd(Nota, na.rm = TRUE), 2),
    percentil_75 = round(quantile(Nota, 0.75, na.rm = TRUE), 2),
    val_max = round(max(Nota, na.rm = TRUE), 2),
  )

tabla_est %>% kable()
```

Relaciones

```{r}
notas <- datos %>% select(ALG, ANM, FP, DCS, MD)

ggpairs(notas, title = "Matriz de Relaciones entre Asignaturas")


cor_pearson <- cor(notas, use = "pairwise.complete.obs", method = "pearson")
cor_pearson 

cov_pearson <- cov(notas, use = "pairwise.complete.obs", method = "pearson")
cov_pearson

cor_spearman <- cor(notas, use = "pairwise.complete.obs", method = "spearman")
cor_spearman

cov_spearman <- cov(notas, use = "complete.obs", method = "spearman")
cov_spearman
```

Las dos variables con la correlación más alta son Álgebra y Análisis Matemático si usamos Pearson, y Matemática Discreta Y Fundamentos de la Programación si usamos Spearman.


Boxplot

```{r}
datos_boxplot <- datos %>%
  select(ALG, ANM, FP, DCS, MD) %>%
  pivot_longer(cols = everything(),
               names_to = "Asignatura",
               values_to = "Nota") %>% 
  filter(!is.na(Nota)) 

ggplot(datos_boxplots, aes(x = Asignatura, y = Nota, fill = Asignatura)) +
  geom_boxplot(alpha = 0.7, outlier.colour = "red") +
  scale_y_continuous(limits = c(0, 10), breaks = seq(0, 10, 1)) +
  labs(title = "Calificaciones por Asignatura",
       x = "Asignatura",
       y = "Nota") +
  theme_minimal()
```

Con sexo

```{r}
datos_boxplot_sexo <- datos %>%
  select(Sex, ALG, ANM, FP, DCS, MD) %>%
  pivot_longer(cols = c(ALG, ANM, FP, DCS, MD),
               names_to = "Asignatura",
               values_to = "Nota") %>% 
  filter(!is.na(Nota)) %>%
  filter(!is.na(Sex))

ggplot(datos_boxplot_sexo, aes(x = Asignatura, y = Nota, fill = Sex)) +
  geom_boxplot(alpha = 0.7, outlier.colour = "red") +
  scale_y_continuous(limits = c(0, 10), breaks = seq(0, 10, 1)) +
  labs(
    title = "Boxplot Asignatura, Notas y Sexo",
    x = "Asignatura",
    y = "Calificación Numérica",
    fill = "Sexo del Alumno") +
  theme_minimal()
```

